services:
  - type: web
    name: chromadb
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: chromadb run --host 0.0.0.0 --port 8000
    envVars:
      - key: CHROMA_SERVER_CORS_ALLOW_ORIGINS
        value: "*"
      - key: CHROMA_SERVER_HTTP_PORT
        value: "8000"
      - key: CHROMA_SERVER_HOST
        value: "0.0.0.0"
